packages:
  - apps/*
  - packages/*

allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  '@scarf/scarf': true
  prisma: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.11.4'
  - '@turbo/darwin-arm64@2.11.4'
  - '@turbo/linux-64@2.11.4'
  - '@turbo/linux-arm64@2.11.4'
  - '@turbo/windows-64@2.11.4'
  - '@turbo/windows-arm64@2.11.4'
  - turbo@2.11.4

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/engines'
  - prisma
